name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  ci:
    uses: preston-bernstein/ci-workflows/.github/workflows/go.yml@v1

  workflows:
    uses: preston-bernstein/ci-workflows/.github/workflows/actions-lint.yml@v1
